<!DOCTYPE html>
<html class="no-js" lang="zh">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Try and Catch - 洛谷</title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<meta name="renderer" content="webkit">
<meta name="csrf-token" content="1573391621:clTV6scDUZjECpFuOeXkaF0aKmujClrfMvxI7KUBUdg=">
<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" media="screen"/>
<link rel="stylesheet" href="https://cdn.luogu.com.cn/fe/loader.css?ver=20191106">
<script>window._feInjection = JSON.parse(decodeURIComponent("%7B%22code%22%3A200%2C%22currentTemplate%22%3A%22ProblemShow%22%2C%22currentData%22%3A%7B%22problem%22%3A%7B%22background%22%3Anull%2C%22description%22%3A%22Vasya%20is%20developing%20his%20own%20programming%20language%20VPL%20%28Vasya%20Programming%20Language%29.%20Right%20now%20he%20is%20busy%20making%20the%20system%20of%20exceptions.%20He%20thinks%20that%20the%20system%20of%20exceptions%20must%20function%20like%20that.%5Cn%5CnThe%20exceptions%20are%20processed%20by%20try-catch-blocks.%20There%20are%20two%20operators%20that%20work%20with%20the%20blocks%3A%5Cn%5Cn1.%20The%20try%20operator.%20It%20opens%20a%20new%20try-catch-block.%5Cn2.%20The%20catch%28%3Cexception%5C%5C_type%3E%2C%20%3Cmessage%3E%29%20operator.%20It%20closes%20the%20try-catch-block%20that%20was%20started%20last%20and%20haven%27t%20yet%20been%20closed.%20This%20block%20can%20be%20activated%20only%20via%20exception%20of%20type%20%3Cexception%5C%5C_type%3E.%20When%20we%20activate%20this%20block%2C%20the%20screen%20displays%20the%20%3Cmessage%3E.%20If%20at%20the%20given%20moment%20there%20is%20no%20open%20try-catch-block%2C%20then%20we%20can%27t%20use%20the%20catch%20operator.%5Cn%5CnThe%20exceptions%20can%20occur%20in%20the%20program%20in%20only%20one%20case%3A%20when%20we%20use%20the%20throw%20operator.%20The%20throw%28%3Cexception%5C%5C_type%3E%29%20operator%20creates%20the%20exception%20of%20the%20given%20type.%5Cn%5CnLet%27s%20suggest%20that%20as%20a%20result%20of%20using%20some%20throw%20operator%20the%20program%20created%20an%20exception%20of%20type%20%24%20a%20%24%20.%20In%20this%20case%20a%20try-catch-block%20is%20activated%2C%20such%20that%20this%20block%27s%20try%20operator%20was%20described%20in%20the%20program%20earlier%20than%20the%20used%20throw%20operator.%20Also%2C%20this%20block%27s%20catch%20operator%20was%20given%20an%20exception%20type%20%24%20a%20%24%20as%20a%20parameter%20and%20this%20block%27s%20catch%20operator%20is%20described%20later%20that%20the%20used%20throw%20operator.%20If%20there%20are%20several%20such%20try-catch-blocks%2C%20then%20the%20system%20activates%20the%20block%20whose%20catch%20operator%20occurs%20earlier%20than%20others.%20If%20no%20try-catch-block%20was%20activated%2C%20then%20the%20screen%20displays%20message%20%5C%22Unhandled%20Exception%5C%22.%5Cn%5CnTo%20test%20the%20system%2C%20Vasya%20wrote%20a%20program%20that%20contains%20only%20try%2C%20catch%20and%20throw%20operators%2C%20one%20line%20contains%20no%20more%20than%20one%20operator%2C%20the%20whole%20program%20contains%20exactly%20one%20throw%20operator.%5Cn%5CnYour%20task%20is%3A%20given%20a%20program%20in%20VPL%2C%20determine%2C%20what%20message%20will%20be%20displayed%20on%20the%20screen.%22%2C%22inputFormat%22%3A%22The%20first%20line%20contains%20a%20single%20integer%3A%20%24%20n%20%24%20%24%20%281%3C%3Dn%3C%3D10%5E%7B5%7D%29%20%24%20the%20number%20of%20lines%20in%20the%20program.%20Next%20%24%20n%20%24%20lines%20contain%20the%20program%20in%20language%20VPL.%20Each%20line%20contains%20no%20more%20than%20one%20operator.%20It%20means%20that%20input%20file%20can%20contain%20empty%20lines%20and%20lines%2C%20consisting%20only%20of%20spaces.%5Cn%5CnThe%20program%20contains%20only%20operators%20try%2C%20catch%20and%20throw.%20It%20is%20guaranteed%20that%20the%20program%20is%20correct.%20It%20means%20that%20each%20started%20try-catch-block%20was%20closed%2C%20the%20catch%20operators%20aren%27t%20used%20unless%20there%20is%20an%20open%20try-catch-block.%20The%20program%20has%20exactly%20one%20throw%20operator.%20The%20program%20may%20have%20spaces%20at%20the%20beginning%20of%20a%20line%2C%20at%20the%20end%20of%20a%20line%2C%20before%20and%20after%20a%20bracket%2C%20a%20comma%20or%20a%20quote%20mark.%5Cn%5CnThe%20exception%20type%20is%20a%20nonempty%20string%2C%20that%20consists%20only%20of%20upper%20and%20lower%20case%20english%20letters.%20The%20length%20of%20the%20string%20does%20not%20exceed%2020%20symbols.%20Message%20is%20a%20nonempty%20string%2C%20that%20consists%20only%20of%20upper%20and%20lower%20case%20english%20letters%2C%20digits%20and%20spaces.%20Message%20is%20surrounded%20with%20quote%20marks.%20Quote%20marks%20shouldn%27t%20be%20printed.%20The%20length%20of%20the%20string%20does%20not%20exceed%2020%20symbols.%5Cn%5CnLength%20of%20any%20line%20in%20the%20input%20file%20does%20not%20exceed%2050%20symbols.%22%2C%22outputFormat%22%3A%22Print%20the%20message%20the%20screen%20will%20show%20after%20the%20given%20program%20is%20executed.%22%2C%22samples%22%3A%5B%5B%228%5Cntry%5Cn%20%20%20%20try%5Cn%20%20%20%20%20%20%20%20throw%20%28%20AE%20%29%20%5Cn%20%20%20%20catch%20%28%20BE%2C%20%26quot%3BBE%20in%20line%203%26quot%3B%29%5Cn%5Cn%20%20%20%20try%5Cn%20%20%20%20catch%28AE%2C%20%26quot%3BAE%20in%20line%205%26quot%3B%29%20%5Cncatch%28AE%2C%26quot%3BAE%20somewhere%26quot%3B%29%5Cn%22%2C%22AE%20somewhere%5Cn%22%5D%2C%5B%228%5Cntry%5Cn%20%20%20%20try%5Cn%20%20%20%20%20%20%20%20throw%20%28%20AE%20%29%20%5Cn%20%20%20%20catch%20%28%20AE%2C%20%26quot%3BAE%20in%20line%203%26quot%3B%29%5Cn%5Cn%20%20%20%20try%5Cn%20%20%20%20catch%28BE%2C%20%26quot%3BBE%20in%20line%205%26quot%3B%29%20%5Cncatch%28AE%2C%26quot%3BAE%20somewhere%26quot%3B%29%5Cn%22%2C%22AE%20in%20line%203%5Cn%22%5D%2C%5B%228%5Cntry%5Cn%20%20%20%20try%5Cn%20%20%20%20%20%20%20%20throw%20%28%20CE%20%29%20%5Cn%20%20%20%20catch%20%28%20BE%2C%20%26quot%3BBE%20in%20line%203%26quot%3B%29%5Cn%5Cn%20%20%20%20try%5Cn%20%20%20%20catch%28AE%2C%20%26quot%3BAE%20in%20line%205%26quot%3B%29%20%5Cncatch%28AE%2C%26quot%3BAE%20somewhere%26quot%3B%29%5Cn%22%2C%22Unhandled%20Exception%5Cn%22%5D%5D%2C%22hint%22%3A%22In%20the%20first%20sample%20there%20are%202%20try-catch-blocks%20such%20that%20try%20operator%20is%20described%20earlier%20than%20throw%20operator%20and%20catch%20operator%20is%20described%20later%20than%20throw%20operator%3A%20try-catch%28BE%2C%5C%22BE%20in%20line%203%5C%22%29%20and%20try-catch%28AE%2C%5C%22AE%20somewhere%5C%22%29.%20Exception%20type%20is%20AE%2C%20so%20the%20second%20block%20will%20be%20activated%2C%20because%20operator%20catch%28AE%2C%5C%22AE%20somewhere%5C%22%29%20has%20exception%20type%20AE%20as%20parameter%20and%20operator%20catch%28BE%2C%5C%22BE%20in%20line%203%5C%22%29%20has%20exception%20type%20BE.%5Cn%5CnIn%20the%20second%20sample%20there%20are%202%20try-catch-blocks%20such%20that%20try%20operator%20is%20described%20earlier%20than%20throw%20operator%20and%20catch%20operator%20is%20described%20later%20than%20throw%20operator%3A%20try-catch%28AE%2C%5C%22AE%20in%20line%203%5C%22%29%20and%20try-catch%28AE%2C%5C%22AE%20somewhere%5C%22%29.%20Exception%20type%20is%20AE%2C%20so%20both%20blocks%20can%20be%20activated%2C%20but%20only%20the%20first%20one%20will%20be%20activated%2C%20because%20operator%20catch%28AE%2C%5C%22AE%20in%20line%203%5C%22%29%20is%20described%20earlier%20than%20catch%28AE%2C%5C%22AE%20somewhere%5C%22%29%5Cn%5CnIn%20the%20third%20sample%20there%20is%20no%20blocks%20that%20can%20be%20activated%20by%20an%20exception%20of%20type%20CE.%22%2C%22provider%22%3A%7B%22uid%22%3A3%2C%22name%22%3A%22%5Cu6d1b%5Cu8c37%22%2C%22slogan%22%3A%22%22%2C%22badge%22%3A%22%22%2C%22isAdmin%22%3Atrue%2C%22color%22%3A%22Purple%22%2C%22ccfLevel%22%3A0%7D%2C%22canEdit%22%3Afalse%2C%22limits%22%3A%7B%22time%22%3A%5B2000%5D%2C%22memory%22%3A%5B256000%5D%7D%2C%22stdCode%22%3A%22%22%2C%22vjudge%22%3A%7B%22origin%22%3A%22CodeForces%22%2C%22link%22%3A%22http%3A%5C%2F%5C%2Fcodeforces.com%5C%2Fproblemset%5C%2Fproblem%5C%2F195%5C%2FC%22%2C%22id%22%3A%22195C%22%7D%2C%22tags%22%3A%5B%5D%2C%22wantsTranslation%22%3Atrue%2C%22totalSubmit%22%3A1%2C%22totalAccepted%22%3A1%2C%22pid%22%3A%22CF195C%22%2C%22title%22%3A%22Try%20and%20Catch%22%2C%22difficulty%22%3A0%2C%22type%22%3A%22CF%22%7D%2C%22contest%22%3Anull%2C%22discussions%22%3A%5B%5D%2C%22bookmarked%22%3Afalse%2C%22vjudgeUsername%22%3Anull%2C%22recommendations%22%3A%5B%5D%2C%22lastLanguage%22%3A%22%22%2C%22lastCode%22%3A%22%22%7D%2C%22currentTitle%22%3A%22Try%20and%20Catch%22%2C%22currentTheme%22%3Anull%7D"));window._feConfigVersion=1572920822;</script>
<script src="https://cdn.luogu.com.cn/fe/loader.js?ver=20191106" charset="utf-8" defer></script>
</head>
<body>
<div id="app">
<div class="lg-container">
<article>
<h1>Try and Catch</h1>
<h2>题目描述</h2>
<div>Vasya is developing his own programming language VPL (Vasya Programming Language). Right now he is busy making the system of exceptions. He thinks that the system of exceptions must function like that.
The exceptions are processed by try-catch-blocks. There are two operators that work with the blocks:
1. The try operator. It opens a new try-catch-block.
2. The catch(<exception\_type>, <message>) operator. It closes the try-catch-block that was started last and haven't yet been closed. This block can be activated only via exception of type <exception\_type>. When we activate this block, the screen displays the <message>. If at the given moment there is no open try-catch-block, then we can't use the catch operator.
The exceptions can occur in the program in only one case: when we use the throw operator. The throw(<exception\_type>) operator creates the exception of the given type.
Let's suggest that as a result of using some throw operator the program created an exception of type $ a $ . In this case a try-catch-block is activated, such that this block's try operator was described in the program earlier than the used throw operator. Also, this block's catch operator was given an exception type $ a $ as a parameter and this block's catch operator is described later that the used throw operator. If there are several such try-catch-blocks, then the system activates the block whose catch operator occurs earlier than others. If no try-catch-block was activated, then the screen displays message "Unhandled Exception".
To test the system, Vasya wrote a program that contains only try, catch and throw operators, one line contains no more than one operator, the whole program contains exactly one throw operator.
Your task is: given a program in VPL, determine, what message will be displayed on the screen.</div>
<h2>输入输出格式</h2>
<h3>输入格式</h3>
<br />
<div>The first line contains a single integer: $ n $ $ (1<=n<=10^{5}) $ the number of lines in the program. Next $ n $ lines contain the program in language VPL. Each line contains no more than one operator. It means that input file can contain empty lines and lines, consisting only of spaces.
The program contains only operators try, catch and throw. It is guaranteed that the program is correct. It means that each started try-catch-block was closed, the catch operators aren't used unless there is an open try-catch-block. The program has exactly one throw operator. The program may have spaces at the beginning of a line, at the end of a line, before and after a bracket, a comma or a quote mark.
The exception type is a nonempty string, that consists only of upper and lower case english letters. The length of the string does not exceed 20 symbols. Message is a nonempty string, that consists only of upper and lower case english letters, digits and spaces. Message is surrounded with quote marks. Quote marks shouldn't be printed. The length of the string does not exceed 20 symbols.
Length of any line in the input file does not exceed 50 symbols.</div>
<h3>输出格式</h3>
<br />
<div>Print the message the screen will show after the given program is executed.</div>
<h2>输入输出样例</h2>
<h3>输入样例 #1</h3>
<pre><code>8
try
    try
        throw ( AE ) 
    catch ( BE, &amp;quot;BE in line 3&amp;quot;)

    try
    catch(AE, &amp;quot;AE in line 5&amp;quot;) 
catch(AE,&amp;quot;AE somewhere&amp;quot;)
</code></pre>
<h3>输出样例 #1</h3>
<pre><code>AE somewhere
</code></pre>
<h3>输入样例 #2</h3>
<pre><code>8
try
    try
        throw ( AE ) 
    catch ( AE, &amp;quot;AE in line 3&amp;quot;)

    try
    catch(BE, &amp;quot;BE in line 5&amp;quot;) 
catch(AE,&amp;quot;AE somewhere&amp;quot;)
</code></pre>
<h3>输出样例 #2</h3>
<pre><code>AE in line 3
</code></pre>
<h3>输入样例 #3</h3>
<pre><code>8
try
    try
        throw ( CE ) 
    catch ( BE, &amp;quot;BE in line 3&amp;quot;)

    try
    catch(AE, &amp;quot;AE in line 5&amp;quot;) 
catch(AE,&amp;quot;AE somewhere&amp;quot;)
</code></pre>
<h3>输出样例 #3</h3>
<pre><code>Unhandled Exception
</code></pre>
<h2>说明</h2>
<div>In the first sample there are 2 try-catch-blocks such that try operator is described earlier than throw operator and catch operator is described later than throw operator: try-catch(BE,"BE in line 3") and try-catch(AE,"AE somewhere"). Exception type is AE, so the second block will be activated, because operator catch(AE,"AE somewhere") has exception type AE as parameter and operator catch(BE,"BE in line 3") has exception type BE.
In the second sample there are 2 try-catch-blocks such that try operator is described earlier than throw operator and catch operator is described later than throw operator: try-catch(AE,"AE in line 3") and try-catch(AE,"AE somewhere"). Exception type is AE, so both blocks can be activated, but only the first one will be activated, because operator catch(AE,"AE in line 3") is described earlier than catch(AE,"AE somewhere")
In the third sample there is no blocks that can be activated by an exception of type CE.</div>
</article>
</div>
</div>
</body>
</html>
